{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "REST API COLECTIVO HIFAS DE GRANA",
        "description": "Servicios para la página web del colectivo Hifas de Grana, la cual se encarga de crear conciencia difundiendo y realizando actividades que generen reflexión hacia el cuidado del medio ambiente.",
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        }
    },
    "host": "hifas-de-grana.onrender.com",
    "basePath": "",
    "tags": [
        {
            "name": "conecta",
            "description": "API para conectar con el formulario"
        },
        {
            "name": "recursos_educativos",
            "description": "API para los recursos educativos"
        },
        {
            "name": "donativos",
            "description": "API para los donativos"
        }
    ],
    "schemes": [
        "https"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/api/usuarios/mostrarTodosUsuarios": {
            "get": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Listado de todos los usuarios en el la base de datos.",
                "description": "<p>Servicio que devuelve la información detallada de todos los usuarios que existen en la base de datos.</p><p>&nbsp;</p><p><em><strong>¿Cuáles son los usuarios existentes en la base de datos?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "id": 1,
                                    "nombre": "Juan Perez",
                                    "correo": "juanp@gmail.com",
                                    "contrasena": "hola123",
                                    "id_puesto": 1
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Usuarios"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    },
                    "parameters": [{
                            "description": "apiKey",
                            "type": "string",
                            "in": "header",
                            "name": "Authorization",
                            "default": "Bearer eyJhbGciOiJIUzI1NiJ9.ZXJpa3VlQGdtYWlsLmNvbQ.v7atXtnZ9F14ahwqCSjYKQirsvjs5aWQ4MrPz-BCBSk"
                        }]
                }
            }
        },
        "/api/usuarios/obtenerUsuario/{id}": {
            "get": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Obtiene un usuario de la base de datos.",
                "description": "<p>Servicio que devuelve la información detallada de un usuario existente en la base de datos.</p><p>&nbsp;</p><p><em><strong>¿Existe el usuario en la base de datos?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "id": 1,
                                    "nombre": "Juan Perez",
                                    "correo": "juanp@gmail.com",
                                    "contrasena": "hola123",
                                    "id_puesto": 1
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Usuario"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "requiered": "true",
                        "description": "Id del ususario.",
                        "type": "number",
                        "default": "0"
                    }
                ]
            }
        },
        "/api/usuarios/crearUsuario": {
            "post": {
                "summary": "Crear un usuario",
                "operationId": "create",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "Usuario",
                        "in": "body",
                        "description": "Usuario agregado",
                        "requiered": true,
                        "schema": {
                            "$ref": "#/definitions/NuevoUsuario"
                        }
                    }
                ],
                "tags": ["Usuarios"],
                "responses": {
                    "200": {
                        "description": "Usuario agregado"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/usuarios/actualizarUsuario/{id}": {
            "put": {
                "summary": "Modifica usuario.",
                "operationId": "update",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id del ususario.",
                        "requiered": true,
                        "default": 0
                    },
                    {
                        "name": "Usuario",
                        "in": "body",
                        "description": "Usuario modificado.",
                        "requiered": true,
                        "schema": {
                            "$ref": "#/definitions/NuevoUsuario"
                        }
                    }
                ],
                "tags": ["Usuarios"],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/usuarios/eliminarUsuario/{id}": {
            "delete": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Elimina un usuario del la base de datos.",
                "description": "<p>Servicio que elimina un usuario existente en la base de datos.</p><p>&nbsp;</p><p><em><strong>¿Qué usuario se eliminará en la base de datos?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "requiered": "true",
                        "description": "Id del ususario.",
                        "type": "number",
                        "default": "0"
                    }
                ]
            }
        },
        "/api/roles/mostrarTodosRoles": {
            "get": {
                "tags": [
                    "Roles"
                ],
                "summary": "Listado de todos los roles en la base de datos",
                "description": "<p>Servicio que devuelve la información detallada de todos los roles que existen en una empresa en el en la base de datos.</p><p>&nbsp;</p><p><em><strong>¿Cuáles son las roles existentes en la base de datos?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "id": 2,
                                    "puesto": "Gerente"
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Roles"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/roles/obtenerRol/{id}": {
            "get": {
                "tags": [
                    "Roles"
                ],
                "summary": "Obtiene un rol dentro de la base de datos.",
                "description": "<p>Servicio que devuelve la información detallada de un rol existente en la base de datos .</p><p>&nbsp;</p><p><em><strong>¿Existe el rol en el la base de datos?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "id": 2,
                                    "puesto": "Gerente"
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Rol"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "requiered": "true",
                        "description": "Id del rol.",
                        "type": "number",
                        "default": "0"
                    }
                ]
            }
        },
        "/api/roles/crearRol": {
            "post": {
                "summary": "Crear un rol",
                "operationId": "create",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "Rol",
                        "in": "body",
                        "description": "Rol agregado",
                        "requiered": true,
                        "schema": {
                            "$ref": "#/definitions/NuevoRol"
                        }
                    }
                ],
                "tags": ["Roles"],
                "responses": {
                    "200": {
                        "description": "Rol agregado"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/roles/actualizarRol/{id}": {
            "put": {
                "summary": "Modifica rol.",
                "operationId": "update",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id del rol.",
                        "requiered": true,
                        "default": 0
                    },
                    {
                        "name": "Rol",
                        "in": "body",
                        "description": "Rol modificado.",
                        "requiered": true,
                        "schema": {
                            "$ref": "#/definitions/NuevoRol"
                        }
                    }
                ],
                "tags": ["Roles"],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/roles/eliminarRol/{id}": {
            "delete": {
                "tags": [
                    "Roles"
                ],
                "summary": "Elimina un rol de la base de datos.",
                "description": "<p>Servicio que elimina un rol existente en la base de datos.</p><p>&nbsp;</p><p><em><strong>¿Qué rol se eliminará en la base de datos?</strong></em></p>",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "requiered": "true",
                        "description": "Id del rol.",
                        "type": "number",
                        "default": "0"
                    }
                ]
            }
        },
        "/api/contacto/crearContacto": {
            "post": {
                "summary": "creando un nuevo contacto",
                "operationId": "crearContacto",
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "contacto",
                        "in": "body",
                        "description": "contacto agregado",
                        "required": true,
                        "shema": {
                            "$ref": "#/definitions/contacto"
                        },
                        "example": {
                            "application/json": {
                                "id": 1,
                                "name": "Juan",
                                "email": "juan.perez@example.com",
                                "message": "Hola, este es un mensaje de prueba."
                            }
                        }
                    }
                ],
                "tags": ["conecta"],
                "responses": {
                    "200": {
                        "description": "contacto agregado",
                        "schema": {
                            "$ref": "#/definitions/contacto"
                        },
                        "examples": {
                            "application/json": {
                                "id": 1,
                                "name": "Juan",
                                "email": "juan.perez@example.com",
                                "message": "Hola, este es un mensaje de prueba."
                            }
                        }
                    },
                    "400": {
                        "description": "Error al agregar contacto"
                    }
                },
                "description": "añade un contacto a la base de datos"
            }
        },
        "/api/contacto/mostrarContactos": {
            "get": {
                "summary": "Muestra a los contactos",
                "operationId": "mostrarContactos",
                "produces": ["application/json"],
                "tags": ["conecta"],
                "responses": {
                    "200": {
                        "description": "contactos",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "rows": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Row"
                                    }
                                }
                            }
                        },
                        "examples": {
                            "application/json": [
                                {
                                    "id": 1,
                                    "name": "Juan",
                                    "email": "juan.perez@example.com",
                                    "message": "Hola, este es un mensaje de prueba."
                                },
                                {
                                    "id": 2,
                                    "name": "Maria",
                                    "email": "maria.gomez@example.com",
                                    "message": "Hola, este es otro mensaje de prueba."
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Error al mostrar contactos"
                    }
                },
                "description": "Muestra a aquellos ususarios interesados en contactar con el colectivo y ser una hifa mas "
            }
        },
        "/api/contacto/eliminarContacto/{id}": {
            "delete": {
                "tags": ["conecta"],
                "summary": "Elimina un contacto",
                "description": "Servicio para eliminar un contacto de la base de datos",
                "responses": {
                    "200": {
                        "description": "contacto eliminado",
                        "schema": {
                            "$ref": "#/definitions/contacto"
                        },
                        "examples": {
                            "application/json": {
                                "id": 1,
                                "name": "Juan",
                                "email": "juan.perez@example.com",
                                "message": "Hola, este es un mensaje de prueba."
                            }
                        }
                    },
                    "400": {
                        "description": "Error al eliminar contacto"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id del contacto",
                        "required": true,
                        "type": "number",
                        "schema": {
                            "$ref": "#/definitions/contacto"
                        }
                    }
                ]
            }
        },
        "/api/contacto/actualizarContacto/{id}": {
            "put": {
                "summary": "Actualiza un contacto",
                "operationId": "actualizarContacto",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id del contacto",
                        "required": true,
                        "type": "integer",
                        "format": "int64"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "description": "El objeto nuevoContacto que se va a actualizar",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nuevoContacto"
                        }
                    }
                ],
                "tags": ["conecta"],
                "responses": {
                    "200": {
                        "description": "contacto actualizado",
                        "schema": {
                            "$ref": "#/definitions/contacto"
                        }
                    },
                    "400": {
                        "description": "Error al actualizar contacto"
                    }
                },
                "description": "Actualiza un contacto"
            }
        },
        "/api/contacto/buscarContacto/{id}": {
            "get": {
                "summary": "Busca un contacto",
                "operationId": "buscarContacto",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id del contacto",
                        "required": true,
                        "shema": {
                            "$ref": "#/definitions/contacto"
                        }
                    }
                ],
                "tags": ["conecta"],
                "responses": {
                    "200": {
                        "description": "contacto encontrado",
                        "schema": {
                            "$ref": "#/definitions/contacto"
                        }
                    },
                    "400": {
                        "description": "Error al buscar contacto"
                    }
                },
                "description": "Busca un contacto"
            }
        },
        "/api/recursos_educativos/crearRecurso_educativo": {
            "post": {
                "summary": "Crea un recurso educativo",
                "operationId": "crearRecurso_educativo",
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "recurso_educativo",
                        "in": "body",
                        "description": "recurso educativo agregado",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recurso_educativo"
                        }
                    }
                ],
                "tags": ["recursos_educativos"],
                "responses": {
                    "200": {
                        "description": "recurso educativo agregado",
                        "schema": {
                            "$ref": "#/definitions/recurso_educativo"
                        }
                    },
                    "400": {
                        "description": "Error al agregar recurso educativo"
                    }
                },
                "description": "Crea un recurso educativo"
            }
        },
        "/api/recursos_educativos/mostrarRecursos_educativos": {
            "get": {
                "summary": "Muestra los recursos educativos",
                "operationId": "mostrarRecursos_educativos",
                "produces": ["application/json"],
                "tags": ["recursos_educativos"],
                "responses": {
                    "200": {
                        "description": "recursos educativos",
                        "schema": {
                            "$ref": "#/definitions/recurso_educativo"
                        }
                    },
                    "400": {
                        "description": "Error al mostrar recursos educativos"
                    }
                },
                "description": "Muestra los recursos educativos"
            }
        },
        "/api/recursos_educativos/eliminarRecurso_educativo/{id}": {
            "delete": {
                "tags": ["recursos_educativos"],
                "summary": "Elimina un recurso educativo",
                "description": "Elimina un recurso educativo",
                "responses": {
                    "200": {
                        "description": "recurso educativo eliminado",
                        "schema": {
                            "$ref": "#/definitions/recurso_educativo"
                        }
                    },
                    "400": {
                        "description": "Error al eliminar recurso educativo"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id del recurso educativo",
                        "required": true,
                        "type": "number",
                        "shema": {
                            "$ref": "#/definitions/recurso_educativo"
                        }
                    }
                ]
            }
        },
        "/api/recursos_educativos/actualizarRecurso_educativo/{id}": {
            "put": {
                "summary": "Actualiza un recurso educativo",
                "operationId": "actualizarRecurso_educativo",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id del recurso educativo",
                        "required": true,
                        "shema": {
                            "$ref": "#/definitions/recurso_educativo"
                        }
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "description": "El objeto nuevoRecurso_educativo que se va a actualizar",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nuevoRecurso_educativo"
                        }
                    }
                ],
                "tags": ["recursos_educativos"],
                "responses": {
                    "200": {
                        "description": "recurso educativo actualizado",
                        "schema": {
                            "$ref": "#/definitions/recurso_educativo"
                        }
                    },
                    "400": {
                        "description": "Error al actualizar recurso educativo"
                    }
                },
                "description": "Actualiza un recurso educativo"
            }
        },
        "/api/donativos/crearDonativo/": {
            "post": {
                "summary": "Crea un donativo",
                "operationId": "crearDonativo",
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "donativo",
                        "in": "body",
                        "description": "donativo agregado",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/donativo"
                        },
                        "example": {
                            "application/json": {
                                "id": 1,
                                "direccion": "123 Calle Principal",
                                "correo_electronico": "hola@gmail.com",
                                "numero_telefono": "1234567890",
                                "fecha_donacion": "2022-01-01T00:00:00Z",
                                "cantidad_donada": 100.0,
                                "estado_donacion": "Aceptado"
                            }
                        }
                    }
                ],
                "tags": ["donativos"],
                "responses": {
                    "200": {
                        "description": "donativo agregado",
                        "schema": {
                            "$ref": "#/definitions/donativo"
                        },
                        "examples": {
                            "application/json": {
                                "id": 1,
                                "direccion": "123 Calle Principal",
                                "correo_electronico": "hola@gmail.com",
                                "numero_telefono": "1234567890",
                                "fecha_donacion": "2022-01-01T00:00:00Z",
                                "cantidad_donada": 100.0,
                                "estado_donacion": "Aceptado"
                            }
                        }
                    },
                    "400": {
                        "description": "Error al agregar donativo"
                    }
                },
                "description": "Crea un donativo"
            }
        },
        "/api/donativos/mostrarDonativos": {
            "get": {
                "summary": "Muestra los donativos",
                "operationId": "mostrarDonativos",
                "produces": ["application/json"],
                "tags": ["donativos"],
                "responses": {
                    "200": {
                        "description": "donativos",
                        "schema": {
                            "$ref": "#/definitions/donativo"
                        },
                        "examples": {
                            "application/json": [
                                {
                                    "id": 1,
                                    "nombre": "Donativo 1",
                                    "cantidad": 100,
                                    "fecha": "2022-01-01"
                                },
                                {
                                    "id": 2,
                                    "nombre": "Donativo 2",
                                    "cantidad": 200,
                                    "fecha": "2022-01-02"
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Error al mostrar donativos"
                    }
                },
                "description": "Muestra los donativos"
            }
        },
        "/api/donativos/eliminarDonativo/{id}": {
            "delete": {
                "tags": ["donativos"],
                "summary": "Elimina un donativo",
                "description": "Elimina un donativo",
                "responses": {
                    "200": {
                        "description": "donativo eliminado",
                        "schema": {
                            "$ref": "#/definitions/donativo"
                        }
                    },
                    "400": {
                        "description": "Error al eliminar donativo"
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id del donativo",
                        "required": true,
                        "type": "number",
                        "shema": {
                            "$ref": "#/definitions/donativo"
                        }
                    }
                ]
            }
        },
        "/api/donativos/actualizarDonativo/{id}": {
            "put": {
                "summary": "Actualiza un donativo",
                "operationId": "actualizarDonativo",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id del donativo",
                        "required": true,
                        "shema": {
                            "$ref": "#/definitions/donativo"
                        }
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "description": "El objeto nuevoDonativo que se va a actualizar",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nuevoDonativo"
                        }
                    }
                ],
                "tags": ["donativos"],
                "responses": {
                    "200": {
                        "description": "donativo actualizado",
                        "schema": {
                            "$ref": "#/definitions/donativo"
                        }
                    },
                    "400": {
                        "description": "Error al actualizar donativo"
                    }
                },
                "description": "Actualiza un donativo"
            }
        }
    },
    "definitions": {
        "Usuario": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "number",
                    "description": "Código que permite identificar al usuario."
                },
                "nombre": {
                    "type": "string",
                    "description": "Nombre del usuario."
                },
                "correo": {
                    "type": "string",
                    "description": "Correo electronico del usuario."
                },
                "contrasena": {
                    "type": "string",
                    "description": "Contraseña para la cuenta del usuario."
                },
                "id_puesto": {
                    "type": "number",
                    "description": "Id del puesto del ususario."
                }
            }
        },
        "Usuarios": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Usuario"
            }
        },
        "NuevoUsuario": {
            "type": "object",
            "properties": {
                "nombre": {
                    "type": "string",
                    "description": "Nombre del usuario."
                },
                "correo": {
                    "type": "string",
                    "description": "Correo electronico del usuario."
                },
                "contrasena": {
                    "type": "string",
                    "description": "Contraseña para la cuenta del usuario."
                },
                "id_puesto": {
                    "type": "number",
                    "description": "Id del puesto del ususario."
                }
            }
        },
        "Rol": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "number",
                    "description": "Código que permite identificar el rol."
                },
                "puesto": {
                    "type": "string",
                    "description": "Nombre del rol."
                }
            }
        },
        "Roles": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Rol"
            }
        },
        "NuevoRol": {
            "type": "object",
            "properties": {
                "puesto": {
                    "type": "string",
                    "description": "Nombre del rol."
                }
            }
        },
        "contacto": {
            "type": "object",
            "propierties": {
                "id": {
                    "type": "integer",
                    "description": "id del contacto"
                },
                "name": {
                    "type": "string",
                    "description": "nombre del contacto"
                },
                "email": {
                    "type": "string",
                    "description": "email del contacto"
                },
                "mensaje": {
                    "type": "string",
                    "description": "mensaje del contacto"
                }
            },
            "example": {
                "application/json": {
                    "id": 1,
                    "name": "Juan",
                    "email": "juan.perez.actualizado@example.com",
                    "message": "Hola, este es un mensaje de prueba actualizado."
                }
            }
        },
        "contactos": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/contacto"
            }
        },
        "nuevoContacto": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "nombre del contacto"
                },
                "email": {
                    "type": "string",
                    "description": "email del contacto"
                },
                "message": {
                    "type": "string",
                    "description": "mensaje del contacto"
                }
            }
        },
        "recurso_educativo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "tipo": {
                    "type": "string"
                },
                "archivo": {
                    "type": "string"
                },
                "autor": {
                    "type": "string"
                },
                "titulo": {
                    "type": "string"
                }
            },
            "example": {
                "id": 1,
                "tipo": "Tipo 1",
                "archivo": "Archivo 1",
                "autor": "Autor 1",
                "titulo": "Titulo 1"
            }
        },
        "recurso_educativos": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/recurso_educativo"
            }
        },
        "nuevoRecurso_educativo": {
            "type": "object",
            "properties": {
                "tipo": {
                    "type": "string"
                },
                "archivo": {
                    "type": "string"
                },
                "autor": {
                    "type": "string"
                },
                "titulo": {
                    "type": "string"
                }
            }
        },
        "donativo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "direccion": {
                    "type": "string"
                },
                "correo_electronico": {
                    "type": "string"
                },
                "numero_telefono": {
                    "type": "string"
                },
                "fecha_donacion": {
                    "type": "string",
                    "format": "date-time"
                },
                "cantidad_donada": {
                    "type": "number",
                    "format": "double"
                },
                "estado_donacion": {
                    "type": "string"
                }
            },
            "example": {
                "id": 1,
                "direccion": "123 Calle Principal",
                "correo_electronico": "donante@example.com",
                "numero_telefono": "1234567890",
                "fecha_donacion": "2022-01-01T00:00:00Z",
                "cantidad_donada": 100.0,
                "estado_donacion": "Aceptado"
            }
        },
        "donativos": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/donativo"
            }
        },
        "nuevoDonativo": {
            "type": "object",
            "properties": {
                "direccion": {
                    "type": "string"
                },
                "correo_electronico": {
                    "type": "string"
                },
                "numero_telefono": {
                    "type": "string"
                },
                "fecha_donacion": {
                    "type": "string",
                    "format": "date-time"
                },
                "cantidad_donada": {
                    "type": "number",
                    "format": "double"
                },
                "estado_donacion": {
                    "type": "string"
                }
            }
        }
    }
}
